# Generated by Django 4.2.10 on 2024-02-26 02:40

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('recipe', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
