# Generated by Django 4.2.10 on 2024-02-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default='0001-01-01 00:01', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
