# Generated by Django 4.2.10 on 2024-02-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_pub_date_alter_recipe_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
